# Generated by Django 3.0.14 on 2022-01-31 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('gender', models.CharField(db_column='gender', max_length=100)),
                ('city', models.CharField(db_column='city', max_length=100)),
                ('country', models.CharField(db_column='country', max_length=100)),
                ('contact', models.IntegerField(max_length=10)),
                ('auth', models.OneToOneField(db_column='auth_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
